version: '3.2'
services:
  go-fiber-starter:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    networks:
      - default-network
    environment:
      APP_ENV: "development"
      PORT: "3333"
      HOST: "0.0.0.0"
      # log level: info, warning, error, fatal
      LOG_LEVEL: "debug"
    volumes:
      - .:/app
      - ~/go/pkg/mod:/go/pkg/mod
    ports:
      - "3333:3333"

networks:
  default-network:
    driver: bridge
